spring:
    banner:
            location: banner.txt
    application:
            name: manage-staff-service
    datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/staffdb
     username: divyansh
     password: 1234
    jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
server:
    port:  8083
logging:
  level:
    com:
      capgemini:
        managestaffservice: INFO