spring:
    banner:
            location: banner.txt
    application:
            name: manage-guest-service
    datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/guestdb
     username: divyansh
     password: 1234
    jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
server:
    port: 8088
logging:
  level:
    com:
      capgemini:
        manageguestservice: INFO